config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :sounds do 
        collection do 
        	post :update_positions
      	end    
      end
    end
  end
end

app/models/spree/sound.rb
module Spree
	class Sound < Asset

    validate :no_attachment_errors

	  has_attached_file :attachment,
                      styles: { 
                         original: { format: :mp3, bitrate: 192000, samplerate: 44100, 
                                     bitrate_adjust: :lowest, samplerate_adjust: :lowest }, 
                      },
                      processors: [:audio_convert],
											url: "/spree/sounds/:id/:style/:basename.:extension",
											path: ":rails_root/public/spree/sounds/:id/:style/:basename.:extension"
    validates_attachment :attachment,
                         :presence => true,
                         :content_type => { :content_type => /\Aaudio/ }

		before_post_process :skip_invalid_audio

    attr_accessor :original_bitrate, :original_samplerate

    def no_attachment_errors
    	unless attachment.errors.empty?
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check sound source file."
        false
      end
    end

    private

    def skip_invalid_audio
    	# TODO: check file to make sure it has audio that ffmpeg can access
      file_path = attachment.queued_for_write[:original].path
      file_info = JSON.parse(`ffprobe -v error #{file_path} -print_format json -show_streams`)
      return false if file_info["streams"].nil? || !file_info["streams"].is_a?(Array)
      file_info["streams"].each do |stream|
        if stream["codec_type"] == "audio"
          self.original_bitrate = stream["bit_rate"]
          self.original_samplerate = stream["sample_rate"]
          return true 
        end
      end
    	false
    end
	end
end

app/controllers/spree/admin/sounds_controller.rb
module Spree
  module Admin
    class SoundsController < ResourceController
      helper Spree::ProductSoundsHelper

      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable

      private

      def location_after_destroy
      	admin_product_sounds_url(@product)
      end

      def location_after_save
      	admin_product_sounds_url(@product)
      end

     	def load_data
     		@product = Product.find_by_slug(params[:product_id])
     		@variants = @product.variants.collect do |variant|
     			[variant.options_text, variant.id]
     		end
     		@variants.insert(0, [Spree.t(:all), @product.master.id])
     	end

     	def set_viewable
     		@sound.viewable_type = 'Spree::Variant'
     		@sound.viewable_id = params[:sound][:viewable_id]
     	end


    end
  end
end

app/helpers/spree/product_sounds_helper.rb
module Spree
  module ProductSoundsHelper

  	def insert_product_sound(sound, params={})
  		options = { skin: 'blue'}.merge(params)
  		metadata = options.keys.map{ |k| "#{k.to_s}:#{options[k].inspect}" }.join(",")
  		link_to sound.alt || "", sound.attachment.url, id: "m#{sound.id}", class: "audio {#{metadata}}"
  	end

  end
end

app/views/spree/admin/products/_sounds.html.erb
<%= content_tag :li, class: ('active' if current == 'Sounds') do %>
  <%= link_to_with_icon 'volume-up', Spree.t(:sounds) ,admin_product_sounds_url(@product) %>
<% end if can?(:admin, Spree::Sound) %>

app/views/spree/admin/sounds/_form.html.erb
<div data-hook="admin_sound_form_fields">
  <div class="five columns alpha">
    <div data-hook="file" class="field">
      <%= f.label Spree.t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.label Spree::Variant.model_name.human %><br>
      <%= f.select :viewable_id, @variants, {}, {:class => 'select2 fullwidth'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label Spree.t(:sound_description) %><br>
    <%= f.text_area :alt, rows: 4, class: "fullwidth" %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/sounds/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Sounds' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @sound } %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_sounds_list), admin_product_sounds_url(@product), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @product, @sound], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_sound">
    <legend align="center"><%= @sound.attachment_file_name%></legend>
    <div data-hook="player" class="field alpha two columns">
      <%= f.label Spree.t(:sound_player) %><br>
      <%= insert_product_sound(@sound, width: 0) %>
    </div>
    <div class="ten columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'icon-refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to Spree.t('actions.cancel'), admin_product_sounds_url(@product), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/sounds/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Sounds'} %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon('plus', Spree.t(:new_sound), new_admin_product_sound_url(@product), :id => 'new_sound_link', :class => 'button') %></li>
<% end %>

<div id="sounds" data-hook></div>

<% unless @product.sounds.any? || @product.variant_sounds.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_sounds_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="sounds_table" data-sortable-link="<%= update_positions_admin_product_sounds_url(@product) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 20%">
      <% if @product.has_variants? %>
        <col style="width: 25%">
      <% end %>
      <col style="width: 35%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="sounds_header">
        <th colspan="2"><%= Spree.t(:filename) %></th>
        <% if @product.has_variants? %>
          <th><%= Spree::Variant.model_name.human %></th>
        <% end %>
        <th><%= Spree.t(:sound_player) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.variant_sounds).each do |sound| %>
        <tr id="<%= spree_dom_id sound %>" data-hook="sounds_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= sound.attachment_file_name %>
          </td>
          <% if @product.has_variants? %>
            <td><%= options_text_for(sound) %></td>
          <% end %>
          <td><%= insert_product_sound(sound, width: 180) %></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_product_sound_url(@product, sound), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete sound, { :url => admin_product_sound_url(@product, sound), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/sounds/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Sounds' } %>

<%= form_for [:admin, @product, @sound], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_sound">
    <legend align="center"><%= Spree.t(:new_sound) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_product_sounds_url(@product), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/sounds/new.js' %>

app/views/spree/products/_product_sounds.html.erb
<% sounds = (@product.sounds + @product.variant_sounds).uniq %>
<% if sounds.any? %>
  <div id="product-sounds" data-hook>
    <h6 class="product-section-title"><%= Spree.t(:product_sounds) %></h6>
    <% @product.sounds.each do |sound| %>
  	  <div><%= insert_product_sound(sound, width: 270) %></div>
  	<% end %>
  	<% if @product.has_variants? %>
  		<% @product.variant_sounds.each do |sound| %>
  			<% next if @product.sounds.include?(sound) %>
   	  	<div><%= insert_product_sound(sound) %></div>
  		<% end %>
  	<% end %>
  </div>


<% end %>